// questions.js - JLPT N5 Grammar Practice Questions

const PRACTICE_QUESTIONS = [
  {
    beforeStar: "わたしは まいにち",
    afterStar: "。",
    options: ["学校", "に", "行き", "ます"],
    correctOrder: [1, 2, 3, 4],
    translation: "I go to school every day.",
    explanation: "Pattern: [Place] + に + [Motion Verb]. Use に for destination with verbs like 行く, 来る, 帰る",
    beforeStarFurigana: "わたしは まいにち",
    afterStarFurigana: "。",
    optionsFurigana: ["学校(がっこう)", "に", "行(い)き", "ます"],
  },
  {
    beforeStar: "わたしは",
    afterStar: "。",
    options: ["が", "食べたい", "です", "すし"],
    correctOrder: [4, 1, 2, 3],
    translation: "I want to eat sushi.",
    explanation: "Pattern: [Noun] + が + [Verb stem + たい]. Use が (not を) with ~たい form",
    beforeStarFurigana: "わたしは",
    afterStarFurigana: "。",
    optionsFurigana: ["が", "食(た)べたい", "です", "すし"],
  },
  {
    beforeStar: "きのう",
    afterStar: "。",
    options: ["見ました", "を", "友だち", "と映画"],
    correctOrder: [3, 4, 2, 1],
    translation: "Yesterday I watched a movie with my friend.",
    explanation: "Pattern: [Person] + と + [Action]. と means 'with' (together with someone)",
    beforeStarFurigana: "きのう",
    afterStarFurigana: "。",
    optionsFurigana: ["見(み)ました", "を", "友(とも)だち", "と映画(えいが)"],
  },
  {
    beforeStar: "この本は",
    afterStar: "。",
    options: ["あの本", "高い", "より", "です"],
    correctOrder: [3, 1, 2, 4],
    translation: "This book is more expensive than that book.",
    explanation: "Comparison: A は B より [Adjective]. Use より to mean 'than' in comparisons",
    beforeStarFurigana: "この本(ほん)は",
    afterStarFurigana: "。",
    optionsFurigana: ["あの本(ほん)", "高(たか)い", "より", "です"],
  },
  {
    beforeStar: "田中さんは",
    afterStar: "。",
    options: ["テニス", "が", "上手", "です"],
    correctOrder: [1, 2, 3, 4],
    translation: "Tanaka-san is good at tennis.",
    explanation: "Pattern: [Noun] + が + 上手/下手/好き/嫌い. These adjectives use が, not は",
    beforeStarFurigana: "田中(たなか)さんは",
    afterStarFurigana: "。",
    optionsFurigana: ["テニス", "が", "上手(じょうず)", "です"],
  },
  {
    beforeStar: "わたしは 日本に",
    afterStar: "。",
    options: ["こと", "が", "ある", "行った"],
    correctOrder: [4, 1, 2, 3],
    translation: "I have been to Japan.",
    explanation: "Experience: [Verb-past] + ことがある means 'have done something before'",
    beforeStarFurigana: "わたしは 日本(にほん)に",
    afterStarFurigana: "。",
    optionsFurigana: ["こと", "が", "ある", "行(い)った"],
  },
  {
    beforeStar: "富士山を",
    afterStar: "か。",
    options: ["こと", "見た", "が", "あります"],
    correctOrder: [2, 1, 3, 4],
    translation: "Have you ever seen Mt. Fuji?",
    explanation: "Experience question: [Verb-past] + ことがありますか asks 'Have you ever...?'",
    beforeStarFurigana: "富士山(ふじさん)を",
    afterStarFurigana: "か。",
    optionsFurigana: ["こと", "見(み)た", "が", "あります"],
  },
  {
    beforeStar: "この料理を",
    afterStar: "。",
    options: ["食べた", "が", "ことは", "ありません"],
    correctOrder: [1, 3, 2, 4],
    translation: "I have never eaten this dish.",
    explanation: "Negative experience: [Verb-past] + ことはありません means 'have never done~'",
    beforeStarFurigana: "この料理(りょうり)を",
    afterStarFurigana: "。",
    optionsFurigana: ["食(た)べた", "が", "ことは", "ありません"],
  },
  {
    beforeStar: "外国で",
    afterStar: "。",
    options: ["働いた", "こと", "が", "あります"],
    correctOrder: [1, 2, 3, 4],
    translation: "I have worked in a foreign country.",
    explanation: "Experience: で marks location of action. [Verb-past] + ことがある shows past experience",
    beforeStarFurigana: "外国(がいこく)で",
    afterStarFurigana: "。",
    optionsFurigana: ["働(はたら)いた", "こと", "が", "あります"],
  },
  {
    beforeStar: "一度も",
    afterStar: "。",
    options: ["会った", "ことが", "ありません", "彼に"],
    correctOrder: [4, 1, 2, 3],
    translation: "I have never met him even once.",
    explanation: "Strong negative: 一度も (not even once) + ことがありません emphasizes never having done something",
    beforeStarFurigana: "一度(いちど)も",
    afterStarFurigana: "。",
    optionsFurigana: ["会(あ)った", "ことが", "ありません", "彼(かれ)に"],
  },
  {
    beforeStar: "あなたは 寿司を",
    afterStar: "か。",
    options: ["こと", "作った", "が", "あります"],
    correctOrder: [2, 1, 3, 4],
    translation: "Have you ever made sushi?",
    explanation: "Experience question: Asking about someone's past experience with ことがありますか",
    beforeStarFurigana: "あなたは 寿司(すし)を",
    afterStarFurigana: "か。",
    optionsFurigana: ["こと", "作(つく)った", "が", "あります"],
  },
  {
    beforeStar: "図書館で",
    afterStar: "。",
    options: ["ください", "話さないで", "を", "日本語"],
    correctOrder: [4, 3, 2, 1],
    translation: "Please don't speak Japanese in the library.",
    explanation: "Negative request: [Verb-ない form] + で + ください means 'please don't~'",
    beforeStarFurigana: "図書館(としょかん)で",
    afterStarFurigana: "。",
    optionsFurigana: ["ください", "話(はな)さないで", "を", "日本語(にほんご)"],
  },
  {
    beforeStar: "ここで",
    afterStar: "。",
    options: ["撮らないで", "ください", "を", "写真"],
    correctOrder: [4, 3, 1, 2],
    translation: "Please don't take photos here.",
    explanation: "Negative request: [Object] + を + [Verb-ない] + で + ください. 撮る → 撮らない → 撮らないで",
    beforeStarFurigana: "ここで",
    afterStarFurigana: "。",
    optionsFurigana: ["撮(と)らないで", "ください", "を", "写真(しゃしん)"],
  },
  {
    beforeStar: "",
    afterStar: "。",
    options: ["忘れないで", "を", "宿題", "ください"],
    correctOrder: [3, 2, 1, 4],
    translation: "Please don't forget your homework.",
    explanation: "Negative request with object: [Noun] + を + [Verb-ない] + で + ください",
    beforeStarFurigana: "",
    afterStarFurigana: "。",
    optionsFurigana: ["忘(わす)れないで", "を", "宿題(しゅくだい)", "ください"],
  },
  {
    beforeStar: "教室で",
    afterStar: "。",
    options: ["ください", "食べないで", "を", "食べ物"],
    correctOrder: [4, 3, 2, 1],
    translation: "Please don't eat food in the classroom.",
    explanation: "Negative request: [Object] + を + [Verb-ない] + で + ください. Rules/prohibitions",
    beforeStarFurigana: "教室(きょうしつ)で",
    afterStarFurigana: "。",
    optionsFurigana: ["ください", "食(た)べないで", "を", "食(た)べ物(もの)"],
  },
  {
    beforeStar: "その話を",
    afterStar: "。",
    options: ["ください", "言わないで", "に", "誰"],
    correctOrder: [4, 3, 2, 1],
    translation: "Please don't tell that story to anyone.",
    explanation: "Negative request with indirect object: [Person] + に + [Verb-ない] + で + ください",
    beforeStarFurigana: "その話(はなし)を",
    afterStarFurigana: "。",
    optionsFurigana: ["ください", "言(い)わないで", "に", "誰(だれ)"],
  },
  {
    beforeStar: "まだ",
    afterStar: "。",
    options: ["帰らないで", "ください", "一人で", "ね"],
    correctOrder: [3, 1, 2, 4],
    translation: "Please don't go home alone yet, okay?",
    explanation: "Negative request: まだ (not yet) + [Adverb] + [Verb-ない] + で + ください + ね (confirmation). で marks means/manner",
    beforeStarFurigana: "まだ",
    afterStarFurigana: "。",
    optionsFurigana: ["帰(かえ)らないで", "ください", "一人(ひとり)で", "ね"],
  },
  {
    beforeStar: "電車の中で",
    afterStar: "。",
    options: ["使わないで", "ください", "を", "電話"],
    correctOrder: [4, 3, 1, 2],
    translation: "Please don't use your phone on the train.",
    explanation: "Negative request: Common public manner rule. [Object] + を + [Verb-ない] + で + ください",
    beforeStarFurigana: "電車(でんしゃ)の中(なか)で",
    afterStarFurigana: "。",
    optionsFurigana: ["使(つか)わないで", "ください", "を", "電話(でんわ)"],
  },
  {
    beforeStar: "ここから 駅",
    afterStar: "。",
    options: ["かかります", "分", "まで", "十"],
    correctOrder: [3, 4, 2, 1],
    translation: "It takes 10 minutes from here to the station.",
    explanation: "Duration: [Time] + かかる means 'to take (time)'. まで means 'until/to'",
    beforeStarFurigana: "ここから 駅(えき)",
    afterStarFurigana: "。",
    optionsFurigana: ["かかります", "分(ふん/ぷん)", "まで", "十(じゅう/じっ)"],
  },
  {
    beforeStar: "",
    afterStar: "買いましょう。",
    options: ["に", "いっしょ", "を", "ケーキ"],
    correctOrder: [2, 1, 4, 3],
    translation: "Let's buy a cake together.",
    explanation: "Pattern: いっしょに means 'together'. ~ましょう is 'let's do~' (invitation)",
    beforeStarFurigana: "",
    afterStarFurigana: "買(か)いましょう。",
    optionsFurigana: ["に", "いっしょ", "を", "ケーキ"],
  },
  {
    beforeStar: "あした",
    afterStar: "つもりです。",
    options: ["友だちに", "会う", "駅で", "三時に"],
    correctOrder: [4, 3, 1, 2],
    translation: "Tomorrow I plan to meet my friend at the station at 3 o'clock.",
    explanation: "Intention: [Time] + [Place] + [Person] + に + [Verb dictionary form] + つもりです. Use に to mark the person you meet",
    beforeStarFurigana: "あした",
    afterStarFurigana: "つもりです。",
    optionsFurigana: ["友(とも)だちに", "会(あ)う", "駅(えき)で", "三時(さんじ)に"],
  },
  {
    beforeStar: "来年",
    afterStar: "つもりです。",
    options: ["大学に", "入る", "東京の", "有名な"],
    correctOrder: [3, 4, 1, 2],
    translation: "I plan to enter a famous university in Tokyo next year.",
    explanation: "Future intention: [Time] + [Modifier] + [Place] + に + [Verb dictionary form] + つもりです",
    beforeStarFurigana: "来年(らいねん)",
    afterStarFurigana: "つもりです。",
    optionsFurigana: ["大学(だいがく)に", "入(はい)る", "東京(とうきょう)の", "有名(ゆうめい)な"],
  },
  {
    beforeStar: "今晩は",
    afterStar: "つもりです。",
    options: ["食べない", "何も", "を", "が"],
    correctOrder: [2, 3, 1, 4],
    translation: "I plan not to eat anything tonight.",
    explanation: "Negative intention: [Verb-ない form] + つもりです means 'plan not to~'",
    beforeStarFurigana: "今晩(こんばん)は",
    afterStarFurigana: "つもりです。",
    optionsFurigana: ["食(た)べない", "何(なに)も", "を", "が"],
  },
  {
    beforeStar: "夏休みに",
    afterStar: "つもりです。",
    options: ["旅行する", "へ", "北海道", "家族と"],
    correctOrder: [4, 3, 2, 1],
    translation: "I plan to travel to Hokkaido with my family during summer vacation.",
    explanation: "Future plan: [Time] + に + [Person] + と + [Place] + へ + [Verb dictionary form] + つもりです",
    beforeStarFurigana: "夏休(なつやす)みに",
    afterStarFurigana: "つもりです。",
    optionsFurigana: ["旅行(りょこう)する", "へ", "北海道(ほっかいどう)", "家族(かぞく)と"],
  },
  {
    beforeStar: "卒業したら",
    afterStar: "つもりです。",
    options: ["仕事を", "探す", "すぐに", "いい"],
    correctOrder: [3, 4, 1, 2],
    translation: "I plan to look for a good job right away after I graduate.",
    explanation: "Conditional + intention: [Condition] + [Adverb] + [Modifier] + [Object] + を + [Verb dictionary form] + つもりです",
    beforeStarFurigana: "卒業(そつぎょう)したら",
    afterStarFurigana: "つもりです。",
    optionsFurigana: ["仕事(しごと)を", "探(さが)す", "すぐに", "いい"],
  },
  {
    beforeStar: "もう",
    afterStar: "つもりです。",
    options: ["タバコを", "吸わない", "絶対に", "これから"],
    correctOrder: [4, 3, 1, 2],
    translation: "I plan to absolutely not smoke anymore from now on.",
    explanation: "Negative intention with もう: もう (anymore) + [Adverbs] + [Object] + を + [Verb-ない] + つもりです for strong decisions to stop",
    beforeStarFurigana: "もう",
    afterStarFurigana: "つもりです。",
    optionsFurigana: ["タバコを", "吸(す)わない", "絶対(ぜったい)に", "これから"],
  },
  {
    beforeStar: "週末に",
    afterStar: "つもりです。",
    options: ["新しい", "パソコン", "買う", "を"],
    correctOrder: [1, 2, 4, 3],
    translation: "I plan to buy a new computer this weekend.",
    explanation: "Future plan: [Time] + に + [Adjective] + [Noun] + を + [Verb dictionary form] + つもりです",
    beforeStarFurigana: "週末(しゅうまつ)に",
    afterStarFurigana: "つもりです。",
    optionsFurigana: ["新(あたら)しい", "パソコン", "買(か)う", "を"],
  },
  {
    beforeStar: "わたしは 父",
    afterStar: "。",
    options: ["もらいました", "から", "を", "時計"],
    correctOrder: [2, 4, 3, 1],
    translation: "I received a watch from my father.",
    explanation: "Receiving: [Person] + から + [Object] + を + もらう means 'receive from~'",
    beforeStarFurigana: "わたしは 父(ちち)",
    afterStarFurigana: "。",
    optionsFurigana: ["もらいました", "から", "を", "時計(とけい)"],
  },
  {
    beforeStar: "この部屋は",
    afterStar: "。",
    options: ["ので", "窓", "が", "明るい"],
    correctOrder: [2, 3, 1, 4],
    translation: "This room is bright because it has windows.",
    explanation: "Reason: ので indicates reason/cause. [Reason] + ので + [Result]",
    beforeStarFurigana: "この部屋(へや)は",
    afterStarFurigana: "。",
    optionsFurigana: ["ので", "窓(まど)", "が", "明(あか)るい"],
  },
  {
    beforeStar: "",
    afterStar: "。",
    options: ["行きます", "に", "図書館", "これから"],
    correctOrder: [4, 3, 2, 1],
    translation: "A: Where are you going? / B: I'm going to the library now.",
    explanation: "Response pattern: これから (from now) + [Place] + に + [Motion verb]",
    beforeStarFurigana: "",
    afterStarFurigana: "。",
    optionsFurigana: ["行(い)きます", "に", "図書館(としょかん)", "これから"],
    isDialogue: true,
    speakerA: "どこへ 行きますか。",
    speakerAFurigana: "どこへ 行(い)きますか。",
  },
  {
    beforeStar: "",
    afterStar: "。",
    options: ["ありません", "お金", "が", "もう"],
    correctOrder: [4, 2, 3, 1],
    translation: "A: Will you buy it? / B: I don't have money anymore.",
    explanation: "Negative statement: もう (anymore) + [Noun] + が + ありません (don't have)",
    beforeStarFurigana: "",
    afterStarFurigana: "。",
    optionsFurigana: ["ありません", "お金(かね)", "が", "もう"],
    isDialogue: true,
    speakerA: "それを 買いますか。",
    speakerAFurigana: "それを 買(か)いますか。",
  },
  {
    beforeStar: "はい、",
    afterStar: "。",
    options: ["弾けます", "を", "少し", "ピアノ"],
    correctOrder: [4, 2, 3, 1],
    translation: "A: Can you play the piano? / B: Yes, I can play a little.",
    explanation: "Ability response: [Noun] + を + 少し (a little) + [Verb potential form]",
    beforeStarFurigana: "はい、",
    afterStarFurigana: "。",
    optionsFurigana: ["弾(ひ)けます", "を", "少(すこ)し", "ピアノ"],
    isDialogue: true,
    speakerA: "ピアノが 弾けますか。",
    speakerAFurigana: "ピアノが 弾(ひ)けますか。",
  },
  {
    beforeStar: "",
    afterStar: "。",
    options: ["かかります", "時間", "ぐらい", "三十分"],
    correctOrder: [4, 3, 2, 1],
    translation: "A: How long does it take? / B: It takes about 30 minutes.",
    explanation: "Duration response: [Time] + ぐらい (about) + [Counter] + かかります (takes)",
    beforeStarFurigana: "",
    afterStarFurigana: "。",
    optionsFurigana: ["かかります", "時間(じかん)", "ぐらい", "三十分(さんじゅっぷん)"],
    isDialogue: true,
    speakerA: "どのぐらい 時間が かかりますか。",
    speakerAFurigana: "どのぐらい 時間(じかん)が かかりますか。",
  },
  {
    beforeStar: "",
    afterStar: "か。",
    options: ["くれません", "を", "教えて", "道"],
    correctOrder: [4, 2, 3, 1],
    translation: "A: Excuse me. / B: Could you tell me the way?",
    explanation: "Request pattern: [Noun] + を + [Verb-て form] + くれませんか (polite request)",
    beforeStarFurigana: "",
    afterStarFurigana: "か。",
    optionsFurigana: ["くれません", "を", "教(おし)えて", "道(みち)"],
    isDialogue: true,
    speakerA: "すみません。",
    speakerAFurigana: "すみません。",
  },
  {
    beforeStar: "",
    afterStar: "。",
    options: ["好きです", "が", "サッカー", "一番"],
    correctOrder: [3, 2, 4, 1],
    translation: "A: What sport do you like? / B: I like soccer the most.",
    explanation: "Preference with superlative: [Noun] + が + 一番 (most) + [Adjective]",
    beforeStarFurigana: "",
    afterStarFurigana: "。",
    optionsFurigana: ["好(す)きです", "が", "サッカー", "一番(いちばん)"],
    isDialogue: true,
    speakerA: "どんな スポーツが 好きですか。",
    speakerAFurigana: "どんな スポーツが 好(す)きですか。",
  },
  {
    beforeStar: "いいえ、",
    afterStar: "。",
    options: ["したこと", "が", "ありません", "まだ"],
    correctOrder: [4, 1, 2, 3],
    translation: "A: Have you been to Kyoto? / B: No, I haven't been there yet.",
    explanation: "Negative experience: まだ (yet) + [Verb-past] + ことがありません (have never)",
    beforeStarFurigana: "いいえ、",
    afterStarFurigana: "。",
    optionsFurigana: ["したこと", "が", "ありません", "まだ"],
    isDialogue: true,
    speakerA: "京都へ 行ったことが ありますか。",
    speakerAFurigana: "京都(きょうと)へ 行(い)ったことが ありますか。",
  },
  {
    beforeStar: "",
    afterStar: "か。",
    options: ["出します", "に", "手紙", "いつ"],
    correctOrder: [4, 3, 2, 1],
    translation: "A: You're writing a letter. / B: When will you send it?",
    explanation: "Time question: いつ (when) + [Noun] + に + [Verb] + か (question)",
    beforeStarFurigana: "",
    afterStarFurigana: "か。",
    optionsFurigana: ["出(だ)します", "に", "手紙(てがみ)", "いつ"],
    isDialogue: true,
    speakerA: "手紙を 書いていますね。",
    speakerAFurigana: "手紙(てがみ)を 書(か)いていますね。",
  },
  {
    beforeStar: "風邪を ひきました。",
    afterStar: "。",
    options: ["ほうがいい", "です", "寝た", "早く"],
    correctOrder: [4, 3, 1, 2],
    translation: "I caught a cold. I should sleep early.",
    explanation: "Advice: [Verb-past] + ほうがいい + です means 'should do~' or 'had better do~'",
    beforeStarFurigana: "風邪(かぜ)を ひきました。",
    afterStarFurigana: "。",
    optionsFurigana: ["ほうがいい", "です", "寝(ね)た", "早(はや)く"],
  },
  {
    beforeStar: "",
    afterStar: "。",
    options: ["ほうがいいです", "食べない", "あまり", "を甘い物"],
    correctOrder: [3, 4, 2, 1],
    translation: "You shouldn't eat too many sweets.",
    explanation: "Negative advice: [Verb-ない form] + ほうがいい means 'should not do~' or 'had better not do~'",
    beforeStarFurigana: "",
    afterStarFurigana: "。",
    optionsFurigana: ["ほうがいいです", "食(た)べない", "あまり", "を甘(あま)い物(もの)"],
  },
  {
    beforeStar: "試験が ありますから、",
    afterStar: "。",
    options: ["勉強した", "ほうがいい", "たくさん", "毎日"],
    correctOrder: [4, 3, 1, 2],
    translation: "Since there's an exam, you should study a lot every day.",
    explanation: "Strong advice with reason: [Reason] + から、[Frequency] + [Amount] + [Verb-past] + ほうがいい",
    beforeStarFurigana: "試験(しけん)が ありますから、",
    afterStarFurigana: "。",
    optionsFurigana: ["勉強(べんきょう)した", "ほうがいい", "たくさん", "毎日(まいにち)"],
  },
  {
    beforeStar: "もう 夜 遅いですから、",
    afterStar: "。",
    options: ["帰らない", "ほうがいい", "一人で", "今日は"],
    correctOrder: [4, 3, 1, 2],
    translation: "It's already late at night, so you shouldn't go home alone today.",
    explanation: "Negative advice: [Time] + [Adverb] + [Verb-ない] + ほうがいい for safety/warning advice",
    beforeStarFurigana: "もう 夜(よる) 遅(おそ)いですから、",
    afterStarFurigana: "。",
    optionsFurigana: ["帰(かえ)らない", "ほうがいい", "一人(ひとり)で", "今日(きょう)は"],
  },
  {
    beforeStar: "",
    afterStar: "。",
    options: ["ほうがいい", "病院に", "行った", "です"],
    correctOrder: [2, 4, 3, 1],
    translation: "You should go to the hospital.",
    explanation: "Medical advice: [Place] + に + [Verb-past] + ほうがいい for recommendations",
    beforeStarFurigana: "",
    afterStarFurigana: "。",
    optionsFurigana: ["ほうがいい", "病院(びょういん)に", "行(い)った", "です"],
  },
  {
    beforeStar: "明日は 雨ですから、",
    afterStar: "。",
    options: ["持って行った", "ほうがいい", "を", "傘"],
    correctOrder: [4, 3, 1, 2],
    translation: "It will rain tomorrow, so you should take an umbrella.",
    explanation: "Practical advice: [Object] + を + [Verb-て form + いく past] + ほうがいい",
    beforeStarFurigana: "明日(あした)は 雨(あめ)ですから、",
    afterStarFurigana: "。",
    optionsFurigana: ["持(も)って行(い)った", "ほうがいい", "を", "傘(かさ)"],
  },
  {
    beforeStar: "",
    afterStar: "よ。",
    options: ["ほうがいい", "飲まない", "を", "あまりお酒"],
    correctOrder: [4, 3, 2, 1],
    translation: "You shouldn't drink too much alcohol.",
    explanation: "Health advice with よ: あまり (too much) + [Noun] + を + [Verb-ない] + ほうがいい",
    beforeStarFurigana: "",
    afterStarFurigana: "よ。",
    optionsFurigana: ["ほうがいい", "飲(の)まない", "を", "あまりお酒(さけ)"],
  },
  {
    beforeStar: "",
    afterStar: "よ。",
    options: ["休んだ", "ほうがいい", "少し", "今すぐ"],
    correctOrder: [4, 3, 1, 2],
    translation: "A: I'm tired. / B: You should rest a little right away.",
    explanation: "Caring advice: [Time] + 少し (a little) + [Verb-past] + ほうがいい + よ (particle for emphasis)",
    beforeStarFurigana: "",
    afterStarFurigana: "よ。",
    optionsFurigana: ["休(やす)んだ", "ほうがいい", "少(すこ)し", "今(いま)すぐ"],
    isDialogue: true,
    speakerA: "疲れました。",
    speakerAFurigana: "疲(つか)れました。",
  },
];
